import ('bubbles.js')

export const heroes = [
  bubbles(),
  cage(),
  connections(),
  current(),
  diagonalStripes(),
  flippedDiamonds(),
  houndstooth(),
  linesInMotion(),
  moroccan(),
  morphingDiamonds(),
  rails(),
  rain(),
  squaresInSquares(),
  stripes(),
  ticTacToe(),
  zigZag(),
  bankNote(),
  boxes(),
  circlesSquares(),
  circuitBoard(),
  diagonalLines(),
  endlessClouds(),
  eyes(),
  floorTile(),
  intersectingCircles(),
  melt(),
  overlappingDiamonds(),
  parkayFloor(),
  polkaDots(),
  signal(),
  slantedStars(),
  wallpaper()
]
